<?php

namespace app\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "project".
 *
 * @property int $project_id
 * @property string $name
 * @property int $department_id
 * @property int $pm_id
 * @property string $description
 * @property string $start_date
 * @property string $end_date
 * @property string $type
 * @property int $status_id
 *
 * @property Department $department
 * @property User $pm
 * @property Status $status
 * @property Task[] $tasks
 * @property WorkingOn[] $workingOns
 */
class Project extends \yii\db\ActiveRecord
{
    public $users_array;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'project';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['department_id', 'pm_id'], 'required'],
            [['department_id', 'pm_id', 'status_id'], 'integer'],
            [['start_date', 'end_date'], 'safe'],
            [['name'], 'string', 'max' => 50],
            [['description'], 'string', 'max' => 5000],
            [['type'], 'string', 'max' => 20],
            [['department_id'], 'exist', 'skipOnError' => true, 'targetClass' => Department::className(), 'targetAttribute' => ['department_id' => 'department_id']],
            [['pm_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['pm_id' => 'user_id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => ProjectStatus::className(), 'targetAttribute' => ['status_id' => 'status_id']],
            [['users_array'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'project_id' => 'Проект',
            'name' => 'Название',
            'department_id' => 'Подразделение',
            'pm_id' => 'Менеджер',
            'description' => 'Описание',
            'start_date' => 'Начало',
            'end_date' => 'Окончание',
            'type' => 'Тип',
            'status_id' => 'Статус',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDepartment()
    {
        return $this->hasOne(Department::className(), ['department_id' => 'department_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPm()
    {
        return $this->hasOne(User::className(), ['user_id' => 'pm_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(ProjectStatus::className(), ['status_id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(Task::className(), ['project_id' => 'project_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWorkingOns()
    {
        return $this->hasMany(WorkingOn::className(), ['project_id' => 'project_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(User::className(), ['user_id' => 'user_id'])
            ->viaTable(WorkingOn::tableName(), ['project_id' => 'project_id']);
    }

    public function afterFind()
    {
        $this->users_array = $this->users; // Пересваивание, массивы должны бать одинаковыми
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if (($this->users_array != $this->users)) { // проверка на пустой массив
            $arr = ArrayHelper::map($this->users, 'id', 'user_id'); // Sql запрос в массив
            if(!empty($this->users_array))
            foreach ($this->users_array as $user) { // Превращаем Sql запрос в массив
                if (!in_array($user, $arr)) { // сверяем массивы и добавляем новые элементы
                    $model = new WorkingOn();
                    $model->project_id = $this->project_id;
                    $model->user_id = $user;
                    $model->save();
                }
                if (isset($arr[$user]) && isset($user)) { // сверяем массивы и удаляем элементы
                    unset($arr[$user]);
                }
            }
            WorkingOn::deleteAll(['user_id' => $arr]); // сверяем массивы и удаляем отсутствующие элементы
        } else {
            //WorkingOn::deleteAll(['project_id' => $this->project_id]); // удаляем все элементы, если был передан пустой массив
        }
    }
}
